### ISSUE TITLE
Add the ability to remove a vote

### ISSUE THREAD

**Issue by ttrenka** [kitsonk/dote#13]
Colin mentioned in the "Let's start using Dote" email thread that the ability to actually remove a vote (as opposed to setting it to +0) might be a good thing...

**Comment by kitsonk** [comment]
This can now be accomplished on the website by clicking on the "depressed" voting button.  This will remove the vote.  It does not cause an e-mail to be sent though, though subsequent e-mails that are generated will reflect the "lack" of votes.  Thanks for the suggestion @csnover.
