### ISSUE TITLE
Have a "timeline" view.

### ISSUE THREAD

**Issue by kitsonk** [kitsonk/dote#16]
@neonstalwart and @bryanforbes suggested a timeline view of dote.  I am taking that to assume each activity is presented in a reverse timeline order, so you would have something like:
- Topic Replace JavaScript with TypeScript for Dojo 2 was **Accepted**
- _jeff_ was assigned as owner on Replace JavaScript with TypeScript for Dojo 2
- _sally_ comment on Replace JavaScript with TypeScript for Dojo 2
- _bob_ voted **+1** on Replace JavaScript with TypeScript for Dojo 2
- Topic Replace JavaScript with TypeScript for Dojo2 created

**Comment by neonstalwart** [comment]
:+1:
